Feature/restaurant page
jpdf00/restaurant-page pull request #1
Opened 2021-04-16 22:33 UTC by jpdf00

The page is dynamically rendered and the content switches from a Home Page, a Menu Page, and a Contact Page.

2021-04-17 09:43 UTC, addod19 requested changes
## Status: Require changes :recycle: :traffic_light: 

Hi @jpdf00, congratulations on this project :muscle: All the modules have been well implemented using the `createElement` and adding appropriate styling to the modules :+1: 
The live link works as expected and the commit messages are also easy to understand. :slightly_smiling_face: However, there are a few comments we need to quick fix. Kindly check the comments below:
- Kindly add the "webpack-dev-server" to enable live reload
- Also, kindly add the necessary script so we can run commands like "npm run dev" etc

Once these are addressed, kindly submit another code review request :smile: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2021-04-17 09:43 UTC, addod19 commented on package.json
> +    "webpack-cli": "^4.6.0"
Kindly add the `webpack-dev-server` so we can enable hot reload functionality

2021-04-17 09:43 UTC, addod19 commented on package.json
> +    "test": "echo \"Error: no test specified\" && exit 1"
Kindly add these scripts `"dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack-dev-server --mode development --open" // optional
`  so we can run commands like `npm run dev/npm run build`

2021-04-18 04:15 UTC, mahmoud717 approved these changes
### STATUS: APPROVED ✔️ ✔️ 

**hi @jpdf00**

**Great job with making all of the requirements. the project is approved, you can go ahead and merge this pull request**

2021-04-19 15:11 UTC, merged